---
version: '3'

services:
    java:
        build:
            context: ./java
            dockerfile: java.Dockerfile
        volumes:
            - myapp:/javaapp/App42PaaS-Java-MySQL-Sample/target

    mysql:
        build: 
            context: ./mysql
            dockerfile: mysql.Dockerfile

            args:
                - MYSQL_DATABASE='mydb'
                - MYSQL_USER='root'
                - MYSQL_PASSWORD='root'
                - MYSQL_ROOT_PASSWORD='root'
        ports:
            - "3306:3306"

        depends_on:
          - java

    tomcat:
        build:
            context: ./tomcat
            dockerfile: tomcat.Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - myapp:/opt/tomcat/webapps
            - ./config/Config.properties:/opt/apache-tomcat-8.5.37/webapps/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT/Config.properties
            - ./config/Config.properties:/opt/apache-tomcat-8.5.37/webapps/Config.properties
            - ./config/Config.properties:/opt/apache-tomcat-8.5.37/ROOT/Config.properties
            - ./config/Config.properties:/opt/tomcat/webapps/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT/Config.properties
            - ./config/Config.properties:/opt/tomcat/webapps/Config.properties
            - ./config/Config.properties:/usr/local/tomcat/ROOT/Config.properties
        depends_on:
            - java
            - mysql

volumes:
    myapp:
